default_config:
logger:
  default: error
  logs:
    custom_components.weatheralerts: debug

sensor:
  - platform: weatheralerts
    state: NJ
    zone: 10
#
#  - platform: weatheralerts
#    state: NJ
#    zone: 10
#
#  - platform: weatheralerts
#    state: NJ
#    zone: 1