default_config:
logger:
  default: error
  logs:
    custom_components.weatheralerts: debug

sensor:
  - platform: weatheralerts
    state: NJ
    zone: 010

  - platform: weatheralerts
    state: NJ
    zone: 11

  - platform: weatheralerts
    state: NJ
    zone: 1