default_config:
logger:
  default: error
  logs:
    custom_components.weatheralerts: debug

sensor:
  - platform: weatheralerts
    state: CA
    zone: 560

  - platform: weatheralerts
    state: LA
    zone: 72